added contents of hibridon flique as of 17/12/2020
These are the contents of hibrid_full.tar that François Lique sent me on 17/12/2020

diff --git a/bin/makefirst b/bin/makefirst
--- a/bin/makefirst
+++ b/bin/makefirst
@@ -1,5 +1,6 @@
 #!/bin/csh -f
-# HIBRIDON makefirst $Revision: 2010.2 $ --- initial install script (this version for G4 and intel macs and i86 Linux)
+# HIBRIDON makefirst $Revision: 2016.1 $ --- initial install script (this version and intel macs and i86 Linux)
+# no longer works for G4 macs
 echo " "
 set basedir=`hibriddir`
 set hib_version = `cat $basedir/VERSION`
@@ -27,15 +28,23 @@ echo " "
   endif
 cd $basedir/bin
 echo " "
-echo "Hibridon 4.3 base directory is $basedir" |tee -a $basedir/bin/makefirst.log
+echo "Hibridon 5.0 base directory is $basedir" |tee -a $basedir/bin/makefirst.log
+echo "Please wait while system parameters are gathered ..."
 set sysname=`uname -s`
 set known='no'
 if $sysname == 'Darwin' then
   set known='yes'
-  system_profiler -detailLevel mini>sysprofile
+ # system_profiler -detailLevel mini>sysprofile
+  system_profiler SPHardwareDataType>&sysprofile
   set opsys = `sw_vers -productVersion`
-  set opsys = `echo $opsys |awk '{printf substr($0,1,4)}'`
+  set opsys = `echo $opsys |awk '{printf substr($0,1,5)}'`
+  if ($opsys != "10.11" && $opsys != "10.10") then
+	echo "Hibridon 5.0 runs only under OSX 10.10 or higher"
+  	echo "Abort install ..."
+ 	exit
+  endif
 endif
+
 if $sysname == 'Linux' then
   set known='yes'
 endif
@@ -52,16 +61,18 @@ endif
 echo " "
 echo "system name is $sysname" |tee -a $basedir/bin/makefirst.log
 echo "machine type is $MACHTYPE" |tee -a $basedir/bin/makefirst.log
-echo "host type is $HOSTTYPE" |tee -a $basedir/bin/makefirst.log
+# HOSTTYPE environmental variable is no longer used in OSX Mavericks or Yosemite
+if $sysname == 'Darwin' then
+   set HOSTTYPE = $MACHTYPE
+else
+   echo "host type is $HOSTTYPE" |tee -a $basedir/bin/makefirst.log
+endif
 echo " "
 if $HOSTTYPE == 'intel-pc' then
    set fchar=`echo $HOSTTYPE | awk '{printf index($0,"-")}'` 
    set cputype=`echo $HOSTTYPE | awk '{printf substr($0,0,'$fchar'-1)}'`
-else if $HOSTTYPE == 'intel-mac' then
-   set fchar=`echo $HOSTTYPE | awk '{printf index($0,"-")}'` 
-   set cputype=`echo $HOSTTYPE | awk '{printf substr($0,0,'$fchar'-1)}'`
-else if $HOSTTYPE == 'powermac' then
-   set cputype = $HOSTTYPE
+else if $HOSTTYPE == 'x86_64' then
+   set cputype = intel-mac
 else if ($HOSTTYPE == 'x86_64-linux' || $HOSTTYPE == 'i386-linux' || $HOSTTYPE == 'i686-linux') then
    set cputype = $HOSTTYPE
 else if $HOSTTYPE == 'ia64-linux' then
@@ -72,7 +83,7 @@ else
 endif
 # set default as no 64 bit integers
 set fi64 = ""
-if $cputype == 'intel' then
+if $cputype == 'intel-mac' then
    set fcompiler="ifort"
    set FS = "-save"
    set opt="-O3"
@@ -87,31 +98,6 @@ if $cputype == 'intel' then
        else if $fcompiler == 'absoft' then
           echo "absoft compiler interface not yet implemented, sorry"
           exit
-          echo -n "   Enter optimization flag:  "
-          set opt=$<
-          echo -n "   Enter static flag:  "
-          set FS=$<
-       else
-          echo "   fortran compiler $fcompiler not found; ABORT" |tee -a $basedir/bin/makefirst.log
-          exit
-       endif
-    endif
-else if $cputype == 'powermac' then
-   set fcompiler="xlf"
-   set fi64 = ""
-   set FS = "-qsave"
-   set opt="-O3"
-   echo -n "Your fortran compiler is $fcompiler $opt $FS, is this correct? [y/n]  "
-   set response=$<
-   if $response == 'n' then
-       echo -n "Enter the name of your fortran compiler:  g95 or absoft:  "
-       set fcompiler=$<
-       if $fcompiler == "g95" then
-          echo -n "   Enter optimization flag:  "
-          set opt=$<
-          echo -n "   Enter static flag:  "
-          set FS=$<
-       else if $fcompiler == "absoft" then
           echo -n "   Enter optimization flag:  "
           set opt=$<
           echo -n "   Enter static flag:  "
@@ -171,7 +157,7 @@ if $fcompiler == 'ifort' then
         else
            echo "You are using 64 bit architecture"
            if $sysname == "Darwin" then
-              if ($opsys == '10.7' || $opsys == '10.6' || $opsys == '10.5') then
+              if ($opsys == '10.11' || $opsys == '10.10') then
                  set fi64 = "-i8"
                  echo "This version of hibridon uses 64 bit integers"
               else
@@ -180,31 +166,15 @@ if $fcompiler == 'ifort' then
            endif
            set fcomposer = `echo $FFC |grep composer`
            if $fcomposer == "" then
-               echo "You are using Intel's ifort version number < 12"
+               echo "You are not using the Intel's Fortran Composer"
            else
-               echo "You are using Intel's new Fortran Composer (ifort v. 12)"
+               echo "You are using Intel's new Fortran Composer"
            endif
         endif
     else
         echo "fortran compiler $fcompiler not found; ABORT" |tee -a $basedir/bin/makefirst.log
         exit
     endif 
-else if $fcompiler == 'xlf' then
-    set FFC=`which xlf`
-    set resp=`echo $FFC |grep -c "not found"`
-    if $resp == 0 then
-       if (-e $FFC) then 
-           echo "Location of fortran compiler is $FFC" |tee -a $basedir/bin/makefirst.log
-           set FC = $FFC
-           set options = "-qextname -qdpc"
-           set FS = "-qsave"
-           set opt="-O3" 
-       else
-           echo "fortran compiler $fcompiler not found" |tee -a $basedir/bin/makefirst.log
-       endif 
-     else
-        echo "fortran compiler $fcompiler not found" |tee -a $basedir/bin/makefirst.log
-     endif 
 else if $fcompiler == 'g95' then
     set FFC=`which g95`
     set resp=`echo $FFC |grep -c "not found"`
@@ -259,16 +229,22 @@ else
     exit
 endif
 echo ""
-if ($HOSTTYPE == 'intel-pc' || $HOSTTYPE == 'intel-mac') then
+if ($HOSTTYPE == 'intel-pc' || $cputype == 'intel-mac') then
    echo -n "Are you using Intel's mklib for lapack and blas? [y/n]  "
    set response1=$<
+
+#edit 11Jul2013
+   if ! $?MKLPATH then
+      set MKLPATH=$MKLROOT/lib
+   endif 
+
    if $response1 == 'y' then
       set BLASLIB=""
       if $flag64 == "false" then
          set fi64=""
          set LAPACKLIB="-L$MKLPATH -lmkl_intel -lmkl_intel_thread -lmkl_core -lmkl_intel_thread -lmkl_core -lmkl_intel_thread -lmkl_core -lguide -lpthread"
       else
-         set f11=`echo $FC | grep 11`
+         set f11=`echo $FC | grep "11\."`
          if $fi64 == "" then
             set LAPACKLIB="-L$MKLPATH -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_intel_thread -lmkl_core -lmkl_intel_thread -lmkl_core -lguide -lpthread"
          else
@@ -301,19 +277,15 @@ else if ($HOSTTYPE == 'x86_64-linux' || $HOSTTYPE == 'ia64-linux' || $HOSTTYPE =
    echo -n "Are you using Intel's mklib for lapack and blas? [y/n]  "
    set response1=$<
    if $response1 == 'y' then
-      echo -n "Are you using Intel x86 Architecture? [y/n]  "
+      echo -n "Are you using Intel IA64 Architecture? [y/n]  "
       set response2=$<
-      if $response2 == 'n' then
+      if $response2 == 'y' then
         set BLASLIB=""
         set LAPACKLIB="-L$LIBRARY_PATH -lmkl_ipf -lmkl_intel_thread -lmkl_core -lguide -openmp"
         goto libprint
       else
         set BLASLIB=""
-        if $fcomposer == "" then
-           set LAPACKLIB="-L$MKLROOT $MKLROOT/libmkl_solver_lp64.a -Wl,--start-group -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -Wl,--end-group -openmp -lpthread"
-        else
-           set LAPACKLIB="-L$MKLROOT  -Wl,--start-group -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -Wl,--end-group -openmp -lpthread"
-        endif
+        set LAPACKLIB="-L$LIBRARY_PATH -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lpthread -liomp5 -lm"
         goto libprint
       endif
    else
@@ -373,7 +345,7 @@ if (-r CONFIG) then
     mv CONFIG CONFIG.BAK
     echo "   Old CONFIG saved as CONFIG.BAK" |tee -a $basedir/bin/makefirst.log
 endif
-if ($HOSTTYPE == 'intel-pc' || $HOSTTYPE == 'intel-mac') then
+if ($HOSTTYPE == 'intel-pc' || $cputype == 'intel-mac') then
    set machine="unix-darwin unix-$fcompiler"
    if $fi64 != "" then
       set machine = "$machine unix-darwin64"
@@ -401,7 +373,8 @@ echo "#                 for architecture $machine" >>CONFIG
 echo "# Machine type .." >>CONFIG
 echo MACH=\"$machine\" >>CONFIG
 echo "# Fortran Compiler .." >>CONFIG
-echo FC=\"$FFC $options\" >>CONFIG
+echo FC=\"$FFC $options -I${basedir}/src\" >>CONFIG
+echo FCPRINT=\"$FFC $options\" >>CONFIG
 echo "# compiler optimisation">>CONFIG
 echo FOPT=\"$opt\" >>CONFIG
 echo "# compiler explicit no optimisation">>CONFIG
